# Generated by Django 4.2.6 on 2023-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='zone',
            name='points_or_radius',
        ),
        migrations.AddField(
            model_name='event',
            name='center',
            field=models.CharField(default='0.0,0.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='hole_points_or_radius',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='points_or_center',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
