# Generated by Django 4.2.6 on 2023-10-19 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_societymessage_remove_zone_points_or_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societymessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='center',
            field=models.CharField(max_length=40),
        ),
    ]
